import { Injectable } from "@angular/core";
import { TranslateService } from "@ngx-translate/core";
import { IPepOption, PepHttpService, PepSessionService } from "@pepperi-addons/ngx-lib";
import { AddonData, DocumentKeyTypes } from "@pepperi-addons/papi-sdk";
import { BaseLogicBlockService } from "src/app/shared/services/base-logic-blocks.service";

@Injectable()
export class SearchDataLogicBlockService extends BaseLogicBlockService {
    
    private _resourcesMap: Map<string, AddonData> = new Map<string, AddonData>();
    private _resourcesDocumentsMap: Map<string, any> = new Map<string, any>();

    get resourcesMap(): ReadonlyMap<string, AddonData> {
        return this._resourcesMap;
    }

    get resourcesDocumentMap(): ReadonlyMap<string, AddonData> {
        return this._resourcesDocumentsMap;
    }

    constructor(
        translate: TranslateService,
        sessionService: PepSessionService,
        httpService: PepHttpService
    ) {
        super(translate, sessionService, httpService);
    }    

    async getResourcesOptions(): Promise<IPepOption[]> {
        const resources = await this.papiClient.resources.resource('resources').get();

        this._resourcesMap = new Map<string, AddonData>(resources.map(resource => [resource.Name, resource]));
        
        const options: IPepOption[] = resources.map(resource => ({ key: resource.Name, value: resource.Name }));
        return options;
    }

    getResourceFieldsOptions(resourceName: string): IPepOption[] {
        let options: IPepOption[] = [];
        const resource = this._resourcesMap.get(resourceName);
        
        if (resource) {
            options = Object.keys(resource.Fields).map(fieldKey => ({ key: fieldKey, value: fieldKey }));
        }

        return options;
    }

    checkDocumentKeyType(resourceName: string): string {
        const resource = this._resourcesMap.get(resourceName);

        if (!resource || !resource.DocumentKey) {
            console.log('Resource or DocumentKey not found:', resourceName);
            return 'NoKey';
        }

        const documentKey = resource.DocumentKey;

        // Check if key is autogenerated
        if (documentKey.Type === DocumentKeyTypes[0]) {
            console.log(`Resource ${resourceName} has ${documentKey.Type} key.`);
            return DocumentKeyTypes[0];
        }

        // Check if key is a composite (by fields)
        if (documentKey.Type === DocumentKeyTypes[1] && Array.isArray(documentKey.Fields)) {
            console.log('Resource has composite key by fields:', resourceName, 'Fields:', documentKey.Fields);
            return DocumentKeyTypes[1];
        }

        console.log('Resource has an unknown or unsupported key type:', resourceName);
        return 'UnknownKeyType';
    }
}
